services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.5.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_FEATURES: preview
#    volumes:
#      - ./.keycloak/intwork-realm.json:/opt/keycloak/data/import/intwork-realm.json:ro
#      - ./.keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
#      - keycloak-data:/opt/keycloak/data
    ports:
      - "8002:8080"
    command: ["start-dev", "--import-realm"]

#volumes:
#  keycloak-data: {}
