logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

server:
  port: 9090
spring:
  application:
    name: gateway
  management:
    endpoints:
      web:
        exposure:
          include: health, info, env, configprops
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
  security:
    oauth2:
      client:
        registration:
          gateway-rest-client:
            client-id: gateway-rest-client
            client-secret: ${GATEWAY_CLIENT_SECRET:TqOwvN7EBjXbX4ymF7v9VV3IftfbcpjM}
            scope:
              - openid
              - profile
              - roles
              - iaka
#              - user:read
#              - user:write
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          gateway-rest-client:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8002/realms/intwork}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8002/realms/intwork}
beminio:
  url: http://localhost:8080
api:
  url: http://localhost:8081
storage:
  url: http://localhost:9000


