apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gateway
  labels:
    app: minio-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-gateway
  template:
    metadata:
      labels:
        app: minio-gateway
    spec:
      containers:
      - name: minio-gateway
        image: gluonstream/minio-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: minio-gateway-config
        env:
        - name: GATEWAY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: gateway-client-secret
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 60
#      hostAliases:
#        - ip: "172.21.0.2"
#          hostnames:
#          - "auth.s4v3.local"
#          - "s4v3.local"
#          - "minio.s4v3.local"
