apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-gateway-ingress
  namespace: minio-gateway
spec:
  ingressClassName: nginx
  rules:
    - host: s4v3.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: minio-gateway
                port:
                  number: 9090
          - path: /  #React App
            pathType: Prefix
            backend:
              service:
                name: react-frontend
                port:
                  number: 80
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: minio-gateway
                port:
                  number: 9090
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: minio-gateway
                port:
                  number: 9090
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: minio-gateway
                port:
                  number: 9090