apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: horus-namespace

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml

labels:
  - includeSelectors: true
    pairs:
      app: minio-gateway
